name: Fly Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
        
      - name: Verify secrets
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}"
          echo "ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}"
          echo "FLY_API_TOKEN=${{ secrets.FLY_API_TOKEN }}" | sha256sum
      - name: Deploy with flyctl
        run: |
          flyctl deploy --remote-only \
            --build-arg DB_URL=${{ secrets.DATABASE_URL }} \
            --build-arg AT_S=${{ secrets.ACCESS_TOKEN_SECRET }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
